### ISSUE TITLE
Cassandra instance ID

### ISSUE THREAD

**Issue by nickoffff** [wikimedia/cassandra-metrics-collector#16]
How to provide -Dcassandra.instance-id=<name> to a packaged Cassandra installation?

**Comment by eevans** [comment]
You could add the property to the bottom of `/etc/cassandra/cassandra-env.sh` with something like the following:

```
JVM_OPTS="$JVM_OPTS -Dcassandra.instance-id=node1"
```

Or, if you are running this on a machine with only a single instance of Cassandra, then it would probably be easier to use the "simple invocation" method documented [here](https://github.com/wikimedia/cassandra-metrics-collector/tree/master#simple-invocation), or ([here](https://github.com/wikimedia/cassandra-metrics-collector/tree/v2#simple-invocation) if you are using the [v2 branch](https://github.com/wikimedia/cassandra-metrics-collector/tree/v2) with Cassandra 2.1.x).

Does that help?

**Comment by nickoffff** [comment]
Yes, thank you.

**Comment by eevans** [comment]
Great; Let me know if you have any other questions
